version: '3.8'
services:
  api:
    build:
      dockerfile: ./Dockerfile.dev
      context: ./containers/api
    depends_on:
      - postgres
    container_name: ${PROJECT_NAME}_api
    restart: unless-stopped
    volumes:
      - ./containers/api:/home/node/app
      - /home/node/app/node_modules
  
  nginx:
    depends_on:
      - api
      - client
    restart: always
    container_name: ${PROJECT_NAME}_webserver
    build:
      dockerfile: Dockerfile
      context: ./containers/nginx
    ports:
      - "${SERVER_PORT}:80"

  client:
    stdin_open: true
    container_name: ${PROJECT_NAME}_client
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./containers/client
    volumes:
      - /app/node_modules
      - ./containers/client:/app

  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: ${PROJECT_NAME}_database_panel
    environment:
        PGADMIN_DEFAULT_EMAIL: "ti@notamedia.com"
        PGADMIN_DEFAULT_PASSWORD: "adminadmin"
    ports:
      - "1080:80"
    depends_on:
      - postgres        